version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 0
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.21.0
    - 7.24.0
  - dependency-name: fastpriorityqueue
    versions:
    - 0.7.0
  - dependency-name: vue2-touch-events
    versions:
    - 3.1.1
    - 3.2.1
  - dependency-name: sharp
    versions:
    - 0.27.1
    - 0.27.2
  - dependency-name: nuxt
    versions:
    - 2.15.0
    - 2.15.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
